export const ADD_HOME_DATA = "ADD_HOME_DATA";
export const ADD_ABOUT_DATA = "ADD_ABOUT_DATA";
export const ADD_SERVICE_DATA = "ADD_SERVICE_DATA";
export const ADD_PLAN_DATA = "ADD_PLAN_DATA";
export const ADD_NEWSBLOG_DATA = "ADD_NEWSBLOG_DATA";
export const ADD_CONTACT_DATA = "ADD_CONTACT_DATA";
export const ADD_POSTS_DATA = "ADD_POSTS_DATA";